### ISSUE TITLE
Remove rust-cpython support

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#2036]
### Discussed in https://github.com/PyO3/maturin/discussions/2031

<div type='discussions-op-text'>

<sup>Originally posted by **henryiii** April  9, 2024</sup>
Currently, there's a list of options when starting a new project that includes `rust-cpython`. Upon inspection, it turns out [that `rust-cpython` was declared abandoned](https://github.com/dgrunwald/rust-cpython) 7 months ago (2+ years since last meaningful commit, not counting this notice) and doesn't support Python 3.12+. There's a note in the readme that projects should move to PyO3.

Shouldn't this be removed from the new project options, to simplify the user choice? Maybe the auto detection code could be removed too, but at least taking it out of the templates seems reasonable at this point. I have actually had someone ask me whether they should pick pyo3 or rust-python a while back because they saw it in this list.</div>

### Phase out plan

- [x] Remove from new/init templates: #2034
- [x] Remove from readme/documentation: #2057
- [x] Remove build support: #2044
