### ISSUE TITLE
Release 0.10

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#463]
## Blockers

- [x] #448 / #461 Auditwheel should pass by default

## Nice to have

If we don't have those I'll need to add a disclaimer to the local path deps feature

- [x] #449 - Failure to package workspace with non-existinent lockilfes 
- [ ] #462 - Additional non-path-dep crates are being packaged in workspaces, causing file not found errors

**Comment by koehlma** [comment]
I would really like to see #449 and #462 fixed because they currently block me from using the official version for packaging and my PR #453 did already include a fix for #462. Let me know if I can be of any help.
