### ISSUE TITLE
TODO list for 1.0

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#796]
maturin is pretty stable as it stands, but I'd like to make some major changes to cli before doing a 1.0 release:

 
 - [x] Switch to no sdist as default, instead add `--sdist` flag. #955
 - [x] Switch to `-i python` as default, instead add `--find-interpreter` flag. Normally you just need to build for one python because that's the python you're testing with. We keep the interpreter search for cases where you want to build all the wheels from one machine/runner. #964 
 - [x] Try replacing `--cargo-extra-args` and `--rustc-extra-args` with `--`, e.g. `maturin build -m snake/Cargo.toml -- --release --features python-bindings -- --cfg mycfg`. I'm not sure if we really want to allow double `--`, but the single version would be much more ergonomic and intuitive. #972 
 - [x] Finish #501: Have python-first packages with a rust module, anchored in pyproject.toml, and rust-first packages that are really just one module exported from rust and maybe some typings, anchored in Cargo.toml. #1185
 - [x] https://github.com/PyO3/maturin/issues/1047
 - [x] cleanup deprecations: https://github.com/PyO3/maturin/pull/1335

**Comment by messense** [comment]
I'd also like to explore https://github.com/PyO3/maturin/pull/756#discussion_r775961992 for `-i pythonX.Y` for well known Python distributions like manylinux and musllinux without the target `pythonX.Y` binary present for **effortless** cross compilation.

**Comment by konstin** [comment]
would that need any backwards incompatible changes?

**Comment by messense** [comment]
> Try replacing --cargo-extra-args and --rustc-extra-args with --

What do you think about just make `maturin build` behave pretty much the same as `cargo rustc` with some additional maturin specific options? @konstin

**Comment by konstin** [comment]
Sounds good!

**Comment by konstin** [comment]
These are all done, anything blocking remaing for having a 1.0 ~soonish?

**Comment by messense** [comment]
I'd like to wait a few months to squash out bugs.

**Comment by messense** [comment]
Will track new issues in 1.0 milestone: https://github.com/PyO3/maturin/milestone/3
