### ISSUE TITLE
Tracking issue for 0.13.0 release

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#989]
- [x] A new setuptools-rust release to fix bootstrap issue in conda-forge https://github.com/PyO3/setuptools-rust/issues/255
- [x] A new beta release to test that maturin bootstraps in conda-forge, see https://github.com/conda-forge/maturin-feedstock/pull/60#issuecomment-1155728686
- [x] New [maturin-action](https://github.com/messense/maturin-action) release to install maturin version specified in `pyproject.toml` to minimize breaking change impact: https://github.com/messense/maturin-action/releases/tag/v1.28.0
- [x] #973

**Comment by messense** [comment]
v0.13.0 is out!
